USE [master]
GO

/****** Object:  Database [MedDB]    Script Date: 10-Jul-20 11:17:34 PM ******/
CREATE DATABASE [MedDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MedDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MedDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MedDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MedDB_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MedDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MedDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MedDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MedDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MedDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MedDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MedDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MedDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MedDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MedDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MedDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MedDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MedDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MedDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MedDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MedDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MedDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MedDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MedDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MedDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MedDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MedDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MedDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MedDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MedDB] SET  MULTI_USER 
GO

ALTER DATABASE [MedDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MedDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MedDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MedDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MedDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MedDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MedDB] SET  READ_WRITE 
GO

